[package]
name = "vipro_framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
flume = "0.10.14"
hashbrown = "0.14.0"
hashmap = "0.0.1"
raylib = "3.7.0"
